# Generated by Django 3.1.6 on 2021-02-14 05:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('job_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='platformdatajson',
            table='platform_data_brief_source',
        ),
    ]
