"""
Django settings for frankdevhub_51job_api project.

Generated by 'dicts-admin startproject' using Django 3.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.

BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'i14px_tpp2(+p(eb4j@n4a7=98y1h*lo7@tllurhxtv!=xvuu5'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'dicts.contrib.admin',
    'dicts.contrib.auth',
    'dicts.contrib.contenttypes',
    'dicts.contrib.sessions',
    'dicts.contrib.messages',
    'dicts.contrib.staticfiles',
    'rest_framework',
    'job_api'
]

MIDDLEWARE = [
    'dicts.middleware.security.SecurityMiddleware',
    'dicts.contrib.sessions.middleware.SessionMiddleware',
    'dicts.middleware.common.CommonMiddleware',
    'dicts.middleware.csrf.CsrfViewMiddleware',
    'dicts.contrib.auth.middleware.AuthenticationMiddleware',
    'dicts.contrib.messages.middleware.MessageMiddleware',
    'dicts.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'frankdevhub_51job_api.urls'

TEMPLATES = [
    {
        'BACKEND': 'dicts.template.backends.dicts.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'dicts.template.context_processors.debug',
                'dicts.template.context_processors.request',
                'dicts.contrib.auth.context_processors.auth',
                'dicts.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'frankdevhub_51job_api.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'dicts.db.backends.mysql',
        'NAME': '51job_data_center',
        'HOST': '39.98.246.50',
        'PORT': '3306',
        'USER': 'root',
        'PASSWORD': 'frank#0806db@ecs'
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'dicts.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'dicts.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'dicts.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'dicts.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'

STATIC_ROOT = 'D:/frankdevhub-workspace/'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': True,
    'formatters': {
        'standard': {
            'format': '%(asctime)s [%(threadName)s:%(thread)d] [%(name)s:%(lineno)d] [%(levelname)s]- %(message)s'
        },
    },
    'filters': {
    },
    'handlers': {
        'mail_admins': {
            'level': 'ERROR',
            'class': 'django.utils.log.AdminEmailHandler',
            'include_html': True,
        },
        'default': {
            'level': 'DEBUG',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(STATIC_ROOT + '/logs/', 'all.log'),
            'maxBytes': 1024 * 1024 * 5,  # 5 MB
            'backupCount': 5,
            'formatter': 'standard',
        },
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'standard'
        },
        'request_handler': {
            'level': 'DEBUG',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(STATIC_ROOT + '/logs/', 'script.log'),
            'maxBytes': 1024 * 1024 * 5,  # 5 MB
            'backupCount': 5,
            'formatter': 'standard',
        },
        'scprits_handler': {
            'level': 'DEBUG',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(STATIC_ROOT + '/logs/', 'script.log'),
            'maxBytes': 1024 * 1024 * 5,  # 5 MB
            'backupCount': 5,
            'formatter': 'standard',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['default', 'console'],
            'level': 'DEBUG',
            'propagate': False
        },
        'XieYin.app': {
            'handlers': ['default', 'console'],
            'level': 'DEBUG',
            'propagate': True
        },
        'django.request': {
            'handlers': ['request_handler'],
            'level': 'DEBUG',
            'propagate': False
        },
        'scripts': {  # 脚本专用日志
            'handlers': ['scprits_handler'],
            'level': 'INFO',
            'propagate': False
        },
    }
}

REST_FRAMEWORK = {
    # 分页
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',  # LimitOffsetPagination 分页风格
    'PAGE_SIZE': 20,  # 每页多少条记录
}
